format = """
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:pine) \
"""

palette = "rose-pine-main"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.rose-pine-main]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.catppuccin-mocha]
overlay = '#313244'
love = '#f38ba8'
gold = '#fab387'
rose = '#eba0ac'
pine = '#74c7ec'
foam = '#94e2d5'
iris = '#cba6f7'

[palettes.bamboo]
overlay = '#2f312c'
love = '#e75a7c'
gold = '#dbb651'
rose = '#f08080'
pine = '#57a5e5'
foam = '#8fb573'
iris = '#aaaaff'

[palettes.tokyonight-moon]
overlay = '#292e42'
love = '#c53b53'
gold = '#ffc777'
rose = '#ff757f'
pine = '#7dcfff'
foam = '#c3e88d'
iris = '#bb9af7'

[palettes.tokyonight-josean]
overlay = '#011628'
love = '#ff4a4a'
gold = '#ffda7b'
rose = '#ff757f'
pine = '#65d1ff'
foam = '#3effdc'
iris = '#ff61ef'

[palettes.lackluster]
overlay = '#191919'
love = '#d70000'
gold = '#ffaa88'
rose = '#deeeed'
pine = '#7788aa'
foam = '#789978'
iris = '#dddddd'

[directory]
format = "[ ](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = false
format = " [](fg:overlay)[ $time ]($style)[ ](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

# Languages

[c]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$environment ]($style)[](fg:overlay)"
disabled = false
symbol = '🅒 '

# add_newline = false
# # A minimal left prompt
# format = """$directory$character"""
# # palette = "catppuccin_mocha"
# # move the rest of the prompt to the right
# right_format = """$all"""
# command_timeout = 1000
#
# [directory.substitutions]
# '~/tests/starship-custom' = 'work-project'
#
# [git_branch]
# format =  '[$symbol$branch(:$remote_branch)]($style)'
#
# [aws]
# format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
# disabled = false
# style = 'bold blue'
# symbol = " "
#
# [golang]
# format = '[ ](bold cyan)'
#
# [kubernetes]
# symbol = '☸ '
# disabled = true
# detect_files = ['Dockerfile']
# format = '[$symbol$context( \($namespace\))]($style) '
# contexts = [
#   { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
# ]
#
# [docker_context]
# disabled = true
#
# # [palettes.catppuccin_mocha]
# # rosewater = "#f5e0dc"
# # flamingo = "#f2cdcd"
# # pink = "#f5c2e7"
# # mauve = "#cba6f7"
# # red = "#f38ba8"
# # maroon = "#eba0ac"
# # peach = "#fab387"
# # yellow = "#f9e2af"
# # green = "#a6e3a1"
# # teal = "#94e2d5"
# # sky = "#89dceb"
# # sapphire = "#74c7ec"
# # blue = "#89b4fa"
# # lavender = "#b4befe"
# # text = "#cdd6f4"
# # subtext1 = "#bac2de"
# # subtext0 = "#a6adc8"
# # overlay2 = "#9399b2"
# # overlay1 = "#7f849c"
# # overlay0 = "#6c7086"
# # surface2 = "#585b70"
# # surface1 = "#45475a"
# # surface0 = "#313244"
# # base = "#1e1e2e"
# # mantle = "#181825"
# # crust = "#11111b"
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:green)'
# error_symbol = '[](bold fg:red)'
# vimcmd_symbol = '[](bold fg:green)'
# vimcmd_replace_one_symbol = '[](bold fg:mauve)'
# vimcmd_replace_symbol = '[](bold fg:mauve)'
# vimcmd_visual_symbol = '[](bold fg:yellow)'
