add_newline = false
# A minimal left prompt
format = """\
$directory\
$character"""
palette = "rose_pine_main"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
disabled = false
success_symbol = '[](bold fg:pine)'
error_symbol = '[](bold fg:love)'
vimcmd_symbol = '[](bold fg:pine)'
vimcmd_replace_one_symbol = '[](bold fg:iris)'
vimcmd_replace_symbol = '[](bold fg:iris)'
vimcmd_visual_symbol = '[](bold fg:gold)'

[directory]
format = "[ $path ]($style)"
style = "bold rose"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ""
format =  '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:iris)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold foam'
symbol = " "

[docker_context]
disabled = true

[palettes.rose_pine_main]
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"
muted = "#6e6a86"
subtle = "#908caa"
text = "#e0def4"
love = "#eb6f92"
gold = "#f6c177"
rose = "#ebbcba"
pine = "#31748f"
foam = "#9ccfd8"
iris = "#c4a7e7"
